### ISSUE TITLE
Project/repo name already used 

### ISSUE THREAD

**Issue by ArnCarveris** [jemc-savi/ECS#1]
Hi, 

to avoid confusion you should pick another name  for repo, there is other project name with same name and that name names sense: 

https://github.com/SanderMertens/flecs

Please before picking name for project make sure it not used, to avoid confusion for users or other problems.

Good luck for your

**Comment by jemc** [comment]
Hi, @ArnCarveris!

Yes, I'm aware of the `SanderMertens/flecs` project, because this repo is planned to be a set of bindings for that project for the Savi language, just like [flecs-lua](https://github.com/flecs-hub/flecs-lua) for the Lua language, [zig-flecs](https://github.com/prime31/zig-flecs) for the Zig language, [flecs-cs](https://github.com/flecs-hub/flecs-cs) for the C# language. and [flecs-rs](https://github.com/jazzay/flecs-rs) for the Rust language.

So I don't think there will be confusion on this point.

**Comment by jemc** [comment]
However, I did actually decide to rename this project to `ECS` - it will still be a wrapper for flecs, but `ECS` will be less typing (e.g. `ECS.Entity` instead of `Flecs.Entity` for type names), and it will more closely match the namespace used by flecs in the C function names (e.g. `ecs_entity_t`).

**Comment by ArnCarveris** [comment]
Ohh I see, why not name it to `flecs-savi`?

**Comment by jemc** [comment]
The `jemc-savi` GitHub org is dedicated to libraries for Savi.

Naming it `jemc-savi/flecs-savi` would be redundant.

At any rate, the `README` now contains a description that should help alleviate any confusion:

> An entity-component-system framework for the Savi language, wrapping the [flecs](https://github.com/SanderMertens/flecs) C library in idiomatic, safe Savi code.
